config/routes.rb
Rails.application.routes.draw do

  root to: "visitors#index"
  get "profile", to: "users#show"

  devise_for :users, controllers: { registrations: "registrations" }

  resources :users
  resources :activities
  resources :activities do
    resources :comments, shallow: true, only: [:index]
  end
  resources :comments, only: [:create]
  resources :participations, only: [:create, :destroy]
  get 'activities/:id/participants' => 'activities#participants', :as => :participants
end

app/models/user.rb
class User < ActiveRecord::Base
  default_scope { order("role ASC, first_name") }
  belongs_to :caregiver, class_name: "User"
  has_many :care_recipients, class_name: "User", foreign_key: "caregiver_id"
  has_many :authored_activities, class_name: "Activity", foreign_key: "author_id"
  has_many :participations, dependent: :destroy
  has_many :joined_activities, through: :participations, source: :activity
  has_many :comments
  enum role: [:admin, :caregiver, :care_recipient]
  enum gender: [:male, :female]
  after_initialize :set_default_role, :if => :new_record?

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :gender, presence: true
  validates :role, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, :if => :address_changed? # auto-fetch coordinates

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  private
  
  def set_default_role
    self.role ||= :care_recipient
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :restrict_caregiver_access, only: :destroy
  before_action :restrict_care_recipient_accesss, except: :show

  def index
    @users = User.all
  end

  def show
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to :back, :notice => "User updated."
    else
      redirect_to :back, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def restrict_care_recipient_accesss
    if current_user.care_recipient?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def restrict_caregiver_access
    if current_user.caregiver?
      redirect_to :back, alert: "Access denied"
    end
  end

  def secure_params
    #FIXME probably not necessary because of devise settings (see registrations_controller)
    params.require(:user).permit(:caregiver_id, :role, :gender, :age, :interests)
  end

end

app/views/users/_user.html.erb
<td>
  <%= link_to user.first_name, user %>
</td>
<td>
  <% if current_user.admin? && current_user != user %>
    <%= form_for(user) do |f| %>
      <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
      <%= f.submit "Change Role", class: "button-xs" %>
    <% end %>
  <% else %>
      <%= user.role %>
  <% end %>
</td>

<td>
  <% if current_user.caregiver? && user.care_recipient? %>
    <% if user.caregiver.nil? %>
      <%= form_for user do |t| %>
        <%= t.hidden_field :caregiver_id, value: current_user.id %>
        <%= t.submit "Add as care-recipient", class: "button-xs" %>
      <% end %>
    <% elsif user.caregiver == current_user %>
      <%= form_for user do |t| %>
        <%= t.hidden_field :caregiver_id, value: nil %>
        <%= t.submit "Remove as care-recipient", class: "button-xs" %>
      <% end %>
    <% else %>
      caregiver: <%= link_to user.caregiver.first_name, user.caregiver %>
    <% end %>
  <% end %>
</td>

<td>
  <% if current_user.admin? %>
    <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => "button-xs") unless user == current_user %>
  <% end %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-12">
      <% if @user == current_user %>
        <h2>My profile</h2>
      <% else %>
        <h2><%= "#{@user.first_name} #{@user.last_name}" %></h2>
      <% end %>
  </div>
</div>
<div class="row">
    <div class="col-md-3">
      <!-- Show role of admins and caregivers only -->
      <% unless @user.care_recipient? %>
        <h4><span class="label label-success"><%= @user.role %></span></h4>
      <% end %>

      <!-- Displayed to admins and caregivers visiting care-recipients' profiles -->
      <% if @user.care_recipient? && !current_user.care_recipient? %>
        <p>
          <strong>Caregiver:</strong>
          <% if @user.caregiver_id.blank? %>
            <i>none</i>
          <% else %>
            <%= link_to @user.caregiver.first_name, @user.caregiver %>
          <% end %>
        </p>
      <% end %>
      <hr>
      <dl class="dl-horizontal user-profile">
        <dt>Age:</dt><dd><%= @user.age %></dd>
        <dt>Gender:</dt><dd><%= @user.gender %></dd>
        <dt>Interests:</dt><dd><%= @user.interests %></dd>
        <dt>E-mail:</dt><dd><%= mail_to @user.email %></dd>
      </dl>
      <%= link_to "Edit profile", edit_user_registration_path, class: "button-xs" if @user == current_user %>

      <!-- Displayed to caregivers visiting their own profile -->
      <% if current_user == @user && @user.caregiver? %>
        <h4>My care-recipients</h4>
        <ul>
          <% @user.care_recipients.each do |person| %>
          <li>
            <% unless person.caregiver.nil? %>
              <%= form_for person do |t| %>
                <%= link_to "#{person.first_name} #{person.last_name}", person %>
                <%= t.hidden_field :caregiver_id, value: nil %>
                <%= t.submit "Remove", class: "button-xs" %>
              <% end %>
            <% end %>
          </li>
          <% end %>

          <% if @user.care_recipients.empty? %>
            <li><i>none</i></li>
          <% end %>
        </ul>
        <%= link_to "Find care-recipients", users_path, class: "button-xs" %>
      <% end %>

      <!-- Displayed to care-recipients visiting teir own profile -->
      <% if current_user == @user && @user.care_recipient? %>  
        <h4>Porposed activities</h4>
        <ul>
          <% @user.authored_activities.each do |activity| %>
            <li><%= link_to activity.title, activity %></li>
          <% end %>
          <% if @user.authored_activities.blank? %>
            <li><i>none</i></li>
          <% end %>
        </ul>
        <%= link_to "Propose Activity", new_activity_path, class: "button-xs" %>

        <h4>Joined activities</h4>
        <ul>
          <% @user.joined_activities.each do |activity| %>
            <li><%= link_to activity.title, activity %></li>
          <% end %>
          <% if @user.joined_activities.blank? %>
            <li><i>none</i></li>
          <% end %>
        </ul>
        <%= link_to "Find Activity", activities_path, class: "button-xs" %>
      <% end %>

      <!-- Displayed to a caregiver visiting an assigned care-recipient's profile -->
      <% if current_user != @user && current_user == @user.caregiver %>
        <h3>User statistics</h3>

        <h4>Activities proposed by <%= @user.first_name %></h4>
        <ul>
          <% @user.authored_activities.each do |activity| %>
            <li><%= link_to activity.title, activity %></li>
          <% end %>
          <% if @user.authored_activities.blank? %>
            <li><i>none</i></li>
          <% end %>
        </ul>

          <h4>Activities <%= @user.first_name %> joined</h4>
        <ul>
          <% @user.joined_activities.each do |activity| %>
            <li><%= link_to activity.title, activity %></li>
          <% end %>
          <% if @user.joined_activities.blank? %>
            <li><i>none</i></li>
          <% end %>
        </ul>

        <pre><strong>Future work:</strong> More sophisticated statistics on the user's activity will go here.</pre>
      <% end %>
    </div>
    <div class="col-md-4">
      <% unless @user.address.blank? %>
        <address>
          <strong>Address:</strong>
          <%= @user.address %><br>
        </address>
        <iframe width="300"
                height="250"
                frameborder="0"
                style="border:0"
                src="https://www.google.com/maps/embed/v1/place?q=<%=@user.address%>&key=<%=ENV['GOOGLE_MAPS_EMBED_KEY']%>">
        </iframe>
      <% end %>
    </div>
    <div class="col-md-5"></div>
</div>