config/routes.rb
Rails.application.routes.draw do

  root to: "visitors#index"
  get "profile", to: "users#show"

  devise_for :users, controllers: { registrations: "registrations" }

  resources :users
  resources :activities
  resources :activities do
    resources :comments, shallow: true, only: [:index]
  end
  resources :comments, only: [:create]
  resources :participations, only: [:create, :destroy]
  get 'activities/:id/participants' => 'activities#participants', :as => :participants
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  default_scope { order('proposed_time ASC') }
  belongs_to :author, class_name: "User"
  has_many :comments 
  has_many :participations, dependent: :destroy
  has_many :participants, through: :participations, source: :user

  before_validation :fill_in_defaults
  validates :author, presence: true
  validates :title, presence: true
  validates :description, presence: true

  geocoded_by :address
  after_validation :geocode, :if => :address_changed? # auto-fetch coordinates

  # Determine wether a user is a participant of the activity.
  #
  # user - The user to check for.
  # Returns true if the user is a participant, or false otherwise.
  def has_participant?(user)
    participants.any? { |p| p.id == user.id }
  end

  private

  def fill_in_defaults
    self.address ||= author.address
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_activity, only: [:participants, :show, :edit, :update, :destroy]

  respond_to :html, :json

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
    respond_with(@activity)
  end

  # GET /activities/:id/participants.json
  def participants
    @activity
    respond_to :json
  end

  # GET /activities/:id
  # GET /activities/:id.json
  def show
    @activity
    @comments = @activity.comments.all
    @comment = @activity.comments.build
    @isAuthor = current_user == @activity.author
    @isParticipant = @activity.has_participant?(current_user)

    respond_with(@activity)
  end

  # GET /activities/new
  def new
    @activity = Activity.new
    respond_to :html
  end

  # GET /activities/:id/edit
  def edit
    unless current_user == @activity.author
      redirect_to activity_path(@activity.id)
    end
    respond_to :html
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.author = current_user
    flash[:notice] = "Activity was successfully created." if @activity.save
    respond_with(@activity)
  end

  # PATCH/PUT /activities/:id
  # PATCH/PUT /activities/:id.json
  def update
    flash[:notice] = "Activity was successfully updated." if @activity.update(activity_params)
    respond_with(@activity)
  end

  # DELETE /activities/:id
  # DELETE /activities/:id.json
  def destroy
    @activity.destroy
    respond_with(@activity)
  end

  private
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:author_id,
                                        :title,
                                        :description,
                                        :proposed_time, 
                                        :address)
    end
end

app/views/activities/_form.html.erb
<%= simple_form_for(@activity) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.datetime_select :proposed_time %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render "form" %>

<%= link_to "Show", @activity %> |
<%= link_to "Back", activities_path %>

app/views/activities/index.html.erb
<div class="row">
    <div class="col-md-12">
        <h1>Proposed Activities</h1>
        <p class="lead">
          Here you’ll find all the activities happening near you. 
          Click on any of the activities to read a detailed description and to join the activity. 
          If you have any questions about a particular activity, just comment below the activity description.
          Happy browsing!
        </p>
        <%= link_to "Propose an Activity yourself!", new_activity_path, class: "btn btn-primary" %>
        <hr>
          <% @activities.each do |activity| %>
        <h4><%= link_to activity.title, activity %></h4>
        <dl class="dl-horizontal">
          <dt>Author</dt>
          <%  author = activity.author.first_name
              author += " (you)" if current_user == activity.author
          %>
          <dd><%= link_to author, activity.author %></dd>
          <dt>Description</dt>
          <dd><%= activity.description %></dd>
          <dt>Proposed time</dt>
          <dd><%= activity.proposed_time.to_formatted_s(:long_ordinal) %></dd>
          <% if current_user == activity.author %>
            <!-- TODO not yet working, looks only for now -->
            <dt><%= button_to "Edit", edit_activity_path(activity), class: "button-xs" %></dt>
            <dd><%= button_to "Destroy", activity, method: :delete, data: { confirm: "Are you sure?" }, class: "button-xs" %></dd>
          <% end %>
        </dl>
        <% end %>
    </div>
</div>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render "form" %>
<%= link_to "Back", activities_path %>

app/views/activities/show.html.erb
<div class="row">
    <div class="col-md-12">
        <h2><%= @activity.title %></h2>
        <%= link_to "Back", activities_path, class: "button-xs" %>
        <%= link_to "Edit", edit_activity_path(@activity), class: "button-xs" if @isAuthor %>
        <br>
        <br>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <dl>
            <dd>
                <b>Proposed by:</b> 
                <%= link_to "#{@activity.author.first_name} #{@activity.author.last_name}", @activity.author %>
            </dd>
            <dd><b>When:</b> <%= @activity.proposed_time.to_formatted_s(:long_ordinal) %></dd>
            <br>
            <dt>Description:</dt>
            <dd><%= @activity.description %></dd>
        </dl>
        <% unless @activity.address.blank? %>
            <address>
              <strong>Where:</strong>
              <%= @activity.address %><br>
            </address>
            <iframe width="300"
                  height="250"
                  frameborder="0"
                  style="border:0"
                  src="https://www.google.com/maps/embed/v1/place?q=<%=@activity.address%>&key=<%=ENV['GOOGLE_MAPS_EMBED_KEY']%>">
            </iframe>
        <% end %>
        </div>
                <div class="col-md-4">
        <h3>Comments</h3>
        <% @comments.each do |comment| %>
          <div>
            <p>
              <strong><%= link_to comment.commenter.first_name, comment.commenter %>:</strong>
              <%= comment.created_at.to_formatted_s(:long_ordinal) %>
              <br>
              <%= comment.body %>
            </p>
          </div>
        <% end %>
        <%= render "comments/form" %>
        </div>
        <div class="col-md-4">
            <h3>Participants:</h3>
            <ul>
                <% @activity.participants.each do |participant| %>
                    <li>
                        <%  display_participant = "#{participant.first_name} #{participant.last_name}"%>
                        <% if participant == current_user %>
                            <% display_participant += " (you)" %>
                            <%= link_to display_participant, participant %>
                            <%= button_to "Cancel participation", {
                                                controller: :participations,
                                                action: :destroy,
                                                activity_id: @activity.id },
                                              method: :delete,
                                              class: "button-xs" %>
                        <% else %>
                            <%= link_to display_participant, participant %>
                        <% end %>
                    </li>
                <% end %>
            </ul>
            <% unless @isParticipant %>
                <%= button_to "Join activity!", {
                                    controller: :participations,
                                    action: :create,
                                    activity_id: @activity.id },
                                  class: "button-xs" %>
            <% end %>
        </div>
        <%- disqus_thread %>
    </div>
</div>