config/routes.rb
Rails.application.routes.draw do

  root to: "visitors#index"
  get "profile", to: "users#show"

  devise_for :users, controllers: { registrations: "registrations" }

  resources :users
  resources :activities
  resources :activities do
    resources :comments, shallow: true, only: [:index]
  end
  resources :comments, only: [:create]
  resources :participations, only: [:create, :destroy]
  get 'activities/:id/participants' => 'activities#participants', :as => :participants
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render "layouts/navigation_links" %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to "Activities", activities_path %></li>
  <% if current_user.admin? || current_user.caregiver? %>
    <li><%= link_to "Users", users_path %></li>
  <% end %>
  <li><%= link_to "My profile (#{current_user.first_name})", profile_path %></li>
  <li><%= link_to "Sign out", destroy_user_session_path, :method=>"delete" %></li>
<% else %>
  <li><%= link_to "Sign in", new_user_session_path %></li>
  <li><%= link_to "Sign up", new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Activityconnect" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Activityconnect" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render "layouts/navigation" %>
    </header>
    <main class="container" role="main">

      <div class="row">
        <div class="col-md-12">
          <%= render "layouts/messages" %>
          <%= disqus_init %>
          <%= yield %>
        </div>
      </div>

    </main>
  </body>
</html>